export const ADD_TO_CART = 'ADD_TO_CART'
export const CHOOSE_TYPE_SEARCH = 'CHOOSE_TYPE_SEARCH'
export const DELETE_TO_CART = 'DELETE_TO_CART'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const GET_LOCATION = 'GET_LOCATION'
export const GEOLOCATION_FAILED = 'GEOLOCATION_FAILED'


